markdown: rdiscount
pygments: true
rdiscount:
  extensions: [smart]

#
# In case of problem with UTF-8 characters, use...
# 	set LC_ALL=fr_FR.UTF-8
# 	set LANG=fr_FR.UTF-8
# ... before launching Jekyll
#

default-locale: en
locales:
  en:
    # Footer
    footer-bb: Built with
    footer-and: and
    footer-hb: Hosted by
    
    # Menus
    menu-lang: Language
    menu-project: Project
    menu-users: Users
    menu-developers: Developers
    menu-search: Search...
    s-menu-download: Download
    s-menu-user-guide: User Guide
    s-menu-support: Support
    s-menu-news: News
    s-menu-what-is-roboconf: What is Roboconf?
    s-menu-license: License
    s-menu-roadmap: Roadmap
    s-menu-use-cases: Use Cases
    s-menu-source-code: Source Code
    s-menu-team: Team
    s-menu-events: Events
    s-menu-graphics: Graphics
    s-menu-links: Links
    s-menu-dev-guide: Developer Guide
    
    # Page names
    events: events
    sources: sources
    team: team
    roadmap: roadmap
    graphics: graphics
    news: news
    what-is-roboconf: roboconf
    license: license
    links: links
    download: download
    support: support
    user-guide: user-guide
    dev-guide: developer-guide
    use-cases: use-cases

  fr:
