encoding: utf-8
markdown: redcarpet
highlighter: pygments
redcarpet:
  extensions: ["tables", "no_intra_emphasis"]


##########################
# Slides.
##########################
slides:
  - about
  - project
  - architecture
  - concepts
  - lamp-example
  - industrial-use-case
  - configuration-files
  - tools
  - links


##########################
# The web site structure.
# Mainly menu names.
##########################

# New locale => translate all the keys.

default-locale: en
locales:
  en:
    icon: gb.png
    language: English
    menu-lang: Language
    menu-project: Project
    menu-users: Users
    menu-developers: Developers
    s-menu-download: Download
    s-menu-user-guide: User Guide
    s-menu-support: Support
    s-menu-news: News
    s-menu-what-is-roboconf: What is Roboconf?
    s-menu-license: License
    s-menu-roadmap: Roadmap
    s-menu-source-code: Source Code
    s-menu-team: Team
    s-menu-events: Events &amp; Publications
    s-menu-academics: Science &amp; University
    s-menu-graphics: Graphics
    s-menu-links: Links
    s-menu-dev-guide: Developer Guide
  
  fr:
    icon: fr.png
    language: Français
    menu-lang: Langage
    menu-project: Projet
    menu-users: Utilisateurs
    menu-developers: Développeurs
    s-menu-download: Télécharger
    s-menu-user-guide: Guide Utilisateur
    s-menu-support: Support
    s-menu-news: Nouveautés
    s-menu-what-is-roboconf: Roboconf
    s-menu-license: Licence
    s-menu-roadmap: Roadmap
    s-menu-source-code: Code Source
    s-menu-team: Équipe
    s-menu-events: Événements &amp; Publications
    s-menu-academics: Science &amp; Universités
    s-menu-graphics: Ressources Graphiques
    s-menu-links: Liens
    s-menu-dev-guide: Guide Développeur


###################################
# Internationalize pages URLs.
# Page URL = Markdown file's name.
###################################

# Translation can be done progressively, page by page
urls:
  
  #
  # User Guide Snapshot
  #
  ug.snapshot.roboconf-architecture:
    en: user-guide/roboconf-architecture
  
  ug.snapshot.configuring-the-web-consoles:
    en: user-guide/configuring-the-web-consoles
  
  ug.snpashot.eclipse-plugin:
    en: user-guide/eclipse-plugin

  ug.snpashot.maven-plugin:
    en: user-guide/maven-plugin
  
  ug.snpashot.reusability:
    en: user-guide/reusability
  
  ug.snapshot.tutorial-getting-started-with-roboconf:
    en: user-guide/tutorial-getting-started-with-roboconf
    fr: guide-utilisateur/tutoriel-debuter-avec-roboconf
  
  ug.snapshot.autonomic-management-with-roboconf:
    en: user-guide/autonomic-management-with-roboconf
  
  ug.snapshot.tutorial-first-deployment-in-the-cloud:
    fr: guide-utilisateur/tutoriel-premier-deploiement-dans-le-cloud
    en: user-guide/tutorial-first-deployment-in-the-cloud
  
  ug.snapshot.tutorial-first-deployment-in-the-cloud-1:
    fr: guide-utilisateur/tutoriel-premier-deploiement-dans-le-cloud-1
    en: user-guide/tutorial-first-deployment-in-the-cloud-1
  
  ug.snapshot.tutorial-first-deployment-in-the-cloud-2:
    fr: guide-utilisateur/tutoriel-premier-deploiement-dans-le-cloud-2
    en: user-guide/tutorial-first-deployment-in-the-cloud-2
  
  ug.snapshot.tutorial-first-deployment-in-the-cloud-3:
    fr: guide-utilisateur/tutoriel-premier-deploiement-dans-le-cloud-3
    en: user-guide/tutorial-first-deployment-in-the-cloud-3
  
  ug.snapshot.tutorial-first-deployment-in-the-cloud-4:
    fr: guide-utilisateur/tutoriel-premier-deploiement-dans-le-cloud-4
    en: user-guide/tutorial-first-deployment-in-the-cloud-4
  
  ug.snapshot.reusable-slides:
    en: user-guide/reusable-slides
    fr: guide-utilisateur/presentation-reutilisable
  
  ug.snapshot.web-administration-screenshots:
    en: user-guide/web-administration-screenshots
  
  ug.snapshot.configuring-the-loggers:
    en: user-guide/configuring-the-loggers
  
  ug.snapshot.installing-the-deployment-manager:
    en: user-guide/installing-the-deployment-manager
  
  ug.snapshot.installing-an-agent:
    en: user-guide/installing-an-agent
  
  ug.snapshot.configuring-the-deployment-manager:
    en: user-guide/configuring-the-deployment-manager
  
  ug.snapshot.configuring-an-agent:
    en: user-guide/configuring-an-agent
  
  ug.snapshot.installing-the-messaging-server:
    en: user-guide/installing-the-messaging-server
  
  ug.snapshot.preparing-virtual-images-with-an-agent:
    en: user-guide/preparing-virtual-images-with-an-agent
  
  ug.snapshot.target-support:
    en: user-guide/target-support
  
  ug.snapshot.list-of-deployment-targets:
    en: user-guide/list-of-deployment-targets
  
  ug.snapshot.target-iaas-openstack:
    en: user-guide/target-iaas-openstack
  
  ug.snapshot.target-jclouds:
    en: user-guide/target-jclouds
  
  ug.snapshot.target-docker:
    en: user-guide/target-docker
  
  ug.snapshot.target-embedded:
    en: user-guide/target-embedded
  
  ug.snapshot.target-iaas-aws:
    en: user-guide/target-iaas-aws
  
  ug.snapshot.target-iaas-vmware:
    en: user-guide/target-iaas-vmware
  
  ug.snapshot.target-iaas-azure:
    en: user-guide/target-iaas-azure
  
  ug.snapshot.target-in-memory:
    en: user-guide/target-in-memory
  
  ug.snapshot.plugins:
    en: user-guide/plugins
  
  ug.snapshot.plugin-logger:
    en: user-guide/plugin-logger
  
  ug.snapshot.plugin-file:
    en: user-guide/plugin-file
  
  ug.snapshot.plugin-bash:
    en: user-guide/plugin-bash
  
  ug.snapshot.plugin-puppet:
    en: user-guide/plugin-puppet
  
  ug.snapshot.roboconf-dsl:
    en: user-guide/roboconf-dsl
  
  ug.snapshot.monitoring-roboconf:
    en: user-guide/monitoring-roboconf
  
  ug.snapshot.monitoring-applications-deployed-with-roboconf:
    en: user-guide/monitoring-applications-deployed-with-roboconf
  
  ug.snapshot.editors:
    en: user-guide/editors
  
  ug.snapshot.configuration-files:
    en: user-guide/configuration-files
  
  ug.snapshot.faq:
    en: user-guide/faq
  
  ug.snapshot.roboconf-concepts:
    en: user-guide/roboconf-concepts
  
  ug.snapshot.application-descriptor:
    en: user-guide/application-descriptor
  
  ug.snapshot.instances-description:
    en: user-guide/instances-description
  
  ug.snapshot.graph-definition:
    en: user-guide/graph-definition
  
  ug.snapshot.graph-resources:
    en: user-guide/graph-resources
  
  ug.snapshot.web-administration:
    en: user-guide/web-administration
  
  ug.snapshot.lamp-example-part-1:
    en: user-guide/lamp-example-part-1
  
  ug.snapshot.lamp-example-part-2:
    en: user-guide/lamp-example-part-2
  
  ug.snapshot.index:
    en: user-guide/user-guide
    fr: guide-utilisateur/guide-utilisateur
  
  ug.snapshot.working-with-roboconf:
    en: user-guide/working-with-roboconf
  
  #
  # Dev' Guide Snapshot
  #
  
  dg.snapshot.index:
    en: developer-guide/developer-guide
    fr: guide-developpeur/guide-developpeur
  
  dg.snapshot.syntax-highlighting:
    en: developer-guide/syntax-highlighting
  
  dg.snapshot.version-management:
    en: developer-guide/version-management
  
  dg.snapshot.ipojo-model:
    en: developer-guide/ipojo-model
  
  dg.snapshot.creating-a-new-roboconf-plugin:
    en: developer-guide/creating-a-new-roboconf-plugin
  
  dg.snapshot.supporting-a-new-deployment-target:
    en: developer-guide/supporting-a-new-deployment-target
  
  dg.snapshot.launching-the-web-administration:
    en: developer-guide/launching-the-web-administration
  
  dg.snapshot.roboconf-model:
    en: developer-guide/roboconf-model
  
  dg.snapshot.continuous-integration:
    en: developer-guide/continuous-integration
  
  dg.snapshot.release-management:
    en: developer-guide/release-management
  
  dg.snapshot.rest-api-application:
    en: developer-guide/rest-api-application
  
  dg.snapshot.rest-api-management:
    en: developer-guide/rest-api-management
  
    dg.snapshot.rest-api-debug:
    en: developer-guide/rest-api-debug
  
  dg.snapshot.web-site-organization:
    en: developer-guide/web-site-organization
  
  dg.snapshot.documenting-a-new-version:
    en: developer-guide/documenting-a-new-version
  
  dg.snapshot.understand-the-messaging-with-rabbit-mq:
    en: developer-guide/understand-the-messaging-with-rabbit-mq
  
  dg.snapshot.debugging-roboconf:
    en: developer-guide/debugging-roboconf
  
  dg.snapshot.life-cycle:
    en: developer-guide/life-cycle
  
  dg.snapshot.development-guidelines:
    en: developer-guide/development-guidelines
  
  #
  # Main pages
  #
  main.events:
    en: events
    fr: evenements
  
  main.academics:
    en: academics
    fr: academiques
  
  main.sources:
    en: sources
    fr: sources
  
  main.team:
    en: team
    fr: equipe
  
  main.roadmap:
    en: roadmap
    fr: roadmap
  
  main.graphics:
    en: graphics
    fr: ressources-graphiques
  
  main.news:
    en: news
    fr: nouveautes
  
  main.what-is-roboconf:
    en: roboconf
    fr: roboconf
  
  main.license:
    en: license
    fr: licence
  
  main.links:
    en: links
    fr: liens
  
  main.download:
    en: download
    fr: telecharger
  
  main.download.changelog:
    en: change-log
    fr: liste-des-changements
  
  main.support:
    en: support
    fr: support
  
  main.user-guide:
    en: user-guide/user-guide
    fr: guide-utilisateur/guide-utilisateur
  
  main.dev-guide:
    en: developer-guide/developer-guide
    fr: guide-developpeur/guide-developpeur
  
    
  #
  # User Guide - Version 0.1
  #
  ug.0.1.reusable-slides:
    en: user-guide-0.1/reusable-slides
  
  ug.0.1.web-administration-screenshots:
    en: user-guide-0.1/web-administration-screenshots
  
  ug.0.1.troubles-installation:
    en: user-guide-0.1/troubles-installation
  
  ug.0.1.installing-the-deployment-manager:
    en: user-guide-0.1/installing-the-deployment-manager
  
  ug.0.1.configuring-the-deployment-manager:
    en: user-guide-0.1/configuring-the-deployment-manager
  
  ug.0.1.installing-the-messaging-server:
    en: user-guide-0.1/installing-the-messaging-server
  
  ug.0.1.launching-the-web-administration:
    en: user-guide-0.1/launching-the-web-administration
  
  ug.0.1.preparing-virtual-images-with-the-agent:
    en: user-guide-0.1/preparing-virtual-images-with-the-agent
  
  ug.0.1.iaas-support:
    en: user-guide-0.1/iaas-support
  
  ug.0.1.iaas-openstack:
    en: user-guide-0.1/iaas-openstack
  
  ug.0.1.iaas-embedded:
    en: user-guide-0.1/iaas-embedded
  
  ug.0.1.iaas-aws:
    en: user-guide-0.1/iaas-aws
  
  ug.0.1.iaas-vmware:
    en: user-guide-0.1/iaas-vmware
  
  ug.0.1.iaas-azure:
    en: user-guide-0.1/iaas-azure
  
  ug.0.1.iaas-localhost:
    en: user-guide-0.1/iaas-localhost
  
  ug.0.1.plugins:
    en: user-guide-0.1/plugins
  
  ug.0.1.plugin-logger:
    en: user-guide-0.1/plugin-logger
  
  ug.0.1.plugin-bash:
    en: user-guide-0.1/plugin-bash
  
  ug.0.1.plugin-puppet:
    en: user-guide-0.1/plugin-puppet
  
  ug.0.1.roboconf-dsl:
    en: user-guide-0.1/roboconf-dsl
  
  ug.0.1.monitoring-roboconf:
    en: user-guide-0.1/monitoring-roboconf
  
  ug.0.1.monitoring-applications-deployed-with-roboconf:
    en: user-guide-0.1/monitoring-applications-deployed-with-roboconf
  
  ug.0.1.editors:
    en: user-guide-0.1/editors
  
  ug.0.1.configuration-files:
    en: user-guide-0.1/configuration-files
  
  ug.0.1.faq:
    en: user-guide-0.1/faq
  
  ug.0.1.roboconf-concepts:
    en: user-guide-0.1/roboconf-concepts
  
  ug.0.1.application-descriptor:
    en: user-guide-0.1/application-descriptor
  
  ug.0.1.instances-description:
    en: user-guide-0.1/instances-description
  
  ug.0.1.graph-definition:
    en: user-guide-0.1/graph-definition
  
  ug.0.1.graph-resources:
    en: user-guide-0.1/graph-resources
  
  ug.0.1.web-administration:
    en: user-guide-0.1/web-administration
  
  ug.0.1.lamp-example-part-1:
    en: user-guide-0.1/lamp-example-part-1
  
  ug.0.1.lamp-example-part-2:
    en: user-guide-0.1/lamp-example-part-2
  
  ug.0.1.working-with-roboconf:
    en: user-guide-0.1/working-with-roboconf
  
  ug.0.1.index:
    en: user-guide-0.1/user-guide
    fr: guide-utilisateur-0.1/guide-utilisateur
 