markdown: redcarpet

#
# In case of problem with UTF-8 characters, use...
# 	set LC_ALL=fr_FR.UTF-8
# 	set LANG=fr_FR.UTF-8
# ... before launching Jekyll
#

##########################
# The web site structure.
# Mainly menu names.
##########################

# New locale => translate all the keys.

default-locale: en
locales:
  en:
    icon: gb.png
    language: English
    menu-lang: Language
    menu-project: Project
    menu-users: Users
    menu-developers: Developers
    menu-search: Search...
    s-menu-download: Download
    s-menu-user-guide: User Guide
    s-menu-support: Support
    s-menu-news: News
    s-menu-what-is-roboconf: What is Roboconf?
    s-menu-license: License
    s-menu-roadmap: Roadmap
    s-menu-source-code: Source Code
    s-menu-team: Team
    s-menu-events: Events & Publications
    s-menu-graphics: Graphics
    s-menu-links: Links
    s-menu-dev-guide: Developer Guide
  
  fr:


###################################
# Internationalize pages URLs.
# Page URL = Markdown file's name.
###################################

# Translation can be done progressively, page by page
urls:
  
  #
  # User Guide Snapshot
  #
  ug.snapshot.installing-the-deployment-manager:
    en: installing-the-deployment-manager
  
  ug.snapshot.installing-the-messaging-server:
    en: installing-the-messaging-server
  
  ug.snapshot.launching-the-web-administration:
    en: launching-the-web-administration
  
  ug.snapshot.preparing-virtual-images-with-the-agent:
    en: preparing-virtual-images-with-the-agent
  
  ug.snapshot.iaas-support:
    en: iaas-support
  
  ug.snapshot.iaas-openstack:
    en: iaas-openstack
  
  ug.snapshot.iaas-aws:
    en: iaas-aws
  
  ug.snapshot.iaas-vmware:
    en: iaas-vmware
  
  ug.snapshot.iaas-azure:
    en: iaas-azure
  
  ug.snapshot.iaas-localhost:
    en: iaas-localhost
  
  ug.snapshot.plugins:
    en: plugins
  
  ug.snapshot.plugin-logger:
    en: plugin-logger
  
  ug.snapshot.plugin-bash:
    en: plugin-bash
  
  ug.snapshot.plugin-puppet:
    en: plugin-puppet
  
  ug.snapshot.editors:
    en: editors
  
  ug.snapshot.configuration-files:
    en: configuration-files
  
  ug.snapshot.faq:
    en: faq
  
  ug.snapshot.roboconf-concepts:
    en: roboconf-concepts
  
  ug.snapshot.application-descriptor:
    en: application-descriptor
  
  ug.snapshot.instances-description:
    en: instances-description
  
  ug.snapshot.graph-definition:
    en: graph-definition
  
  #
  # Dev' Guide Snapshot
  #
  
  #
  # Main pages
  #
  main.events:
    en: events
  
  main.sources:
    en: sources
  
  main.team:
    en: team
  
  main.roadmap:
    en: roadmap
  
  main.graphics:
    en: graphics
  
  main.news:
    en: news
  
  main.what-is-roboconf:
    en: roboconf
  
  main.license:
    en: license
  
  main.links:
    en: links
  
  main.download:
    en: download
  
  main.support:
    en: support
  
  main.user-guide:
    en: user-guide
  
  main.dev-guide:
    en: developer-guide
