encoding: utf-8
markdown: redcarpet

#
# In case of problem with UTF-8 characters, use...
# 	set LC_ALL=fr_FR.UTF-8
# 	set LANG=fr_FR.UTF-8
# ... before launching Jekyll
#

##########################
# The web site structure.
# Mainly menu names.
##########################

# New locale => translate all the keys.

default-locale: en
locales:
  en:
    icon: gb.png
    language: English
    menu-lang: Language
    menu-project: Project
    menu-users: Users
    menu-developers: Developers
    menu-search: Search...
    s-menu-download: Download
    s-menu-user-guide: User Guide
    s-menu-support: Support
    s-menu-news: News
    s-menu-what-is-roboconf: What is Roboconf?
    s-menu-license: License
    s-menu-roadmap: Roadmap
    s-menu-source-code: Source Code
    s-menu-team: Team
    s-menu-events: Events &amp; Publications
    s-menu-graphics: Graphics
    s-menu-links: Links
    s-menu-dev-guide: Developer Guide
  
  fr:
    icon: fr.png
    language: Français
    menu-lang: Langage
    menu-project: Projet
    menu-users: Utilisateurs
    menu-developers: Développeurs
    menu-search: Rechercher...
    s-menu-download: Télécharger
    s-menu-user-guide: Guide Utilisateur
    s-menu-support: Support
    s-menu-news: Nouveautés
    s-menu-what-is-roboconf: Roboconf
    s-menu-license: Licence
    s-menu-roadmap: Roadmap
    s-menu-source-code: Code Source
    s-menu-team: Équipe
    s-menu-events: Événements &amp; Publications
    s-menu-graphics: Ressources Graphiques
    s-menu-links: Liens
    s-menu-dev-guide: Guide Développeur


###################################
# Internationalize pages URLs.
# Page URL = Markdown file's name.
###################################

# Translation can be done progressively, page by page
urls:
  
  #
  # User Guide Snapshot
  #
  ug.snapshot.installing-the-deployment-manager:
    en: user-guide/installing-the-deployment-manager
  
  ug.snapshot.installing-the-messaging-server:
    en: user-guide/installing-the-messaging-server
  
  ug.snapshot.launching-the-web-administration:
    en: user-guide/launching-the-web-administration
  
  ug.snapshot.preparing-virtual-images-with-the-agent:
    en: user-guide/preparing-virtual-images-with-the-agent
  
  ug.snapshot.iaas-support:
    en: user-guide/iaas-support
  
  ug.snapshot.iaas-openstack:
    en: user-guide/iaas-openstack
  
  ug.snapshot.iaas-aws:
    en: user-guide/iaas-aws
  
  ug.snapshot.iaas-vmware:
    en: user-guide/iaas-vmware
  
  ug.snapshot.iaas-azure:
    en: user-guide/iaas-azure
  
  ug.snapshot.iaas-localhost:
    en: user-guide/iaas-localhost
  
  ug.snapshot.plugins:
    en: user-guide/plugins
  
  ug.snapshot.plugin-logger:
    en: user-guide/plugin-logger
  
  ug.snapshot.plugin-bash:
    en: user-guide/plugin-bash
  
  ug.snapshot.plugin-puppet:
    en: user-guide/plugin-puppet
  
  ug.snapshot.editors:
    en: user-guide/editors
  
  ug.snapshot.configuration-files:
    en: user-guide/configuration-files
  
  ug.snapshot.faq:
    en: user-guide/faq
  
  ug.snapshot.roboconf-concepts:
    en: user-guide/roboconf-concepts
  
  ug.snapshot.application-descriptor:
    en: user-guide/application-descriptor
  
  ug.snapshot.instances-description:
    en: user-guide/instances-description
  
  ug.snapshot.graph-definition:
    en: user-guide/graph-definition
  
  ug.snapshot.graph-resources:
    en: user-guide/graph-resources
  
  ug.snapshot.web-administration:
    en: user-guide/web-administration
  
  ug.snapshot.lamp-example:
    en: user-guide/lamp-example
  
  ug.snapshot.index:
    en: user-guide/user-guide
    fr: guide-utilisateur/guide-utilisateur
  
  #
  # Dev' Guide Snapshot
  #
  
  dg.snapshot.index:
    en: developer-guide/developer-guide
    fr: guide-developpeur/guide-developpeur
  
  #
  # Main pages
  #
  main.events:
    en: events
    fr: evenements
  
  main.sources:
    en: sources
    fr: sources
  
  main.team:
    en: team
    fr: equipe
  
  main.roadmap:
    en: roadmap
    fr: roadmap
  
  main.graphics:
    en: graphics
    fr: ressources-graphiques
  
  main.news:
    en: news
    fr: nouveautes
  
  main.what-is-roboconf:
    en: roboconf
    fr: roboconf
  
  main.license:
    en: license
    fr: licence
  
  main.links:
    en: links
    fr: liens
  
  main.download:
    en: download
    fr: telecharger
  
  main.support:
    en: support
    fr: support
  
  main.user-guide:
    en: user-guide/user-guide
    fr: guide-utilisateur/guide-utilisateur
  
  main.dev-guide:
    en: developer-guide/developer-guide
    fr: guide-developpeur/guide-developpeur
